function getCityList(cityList) {
    cityList.push('Aberdeen, SD')
    cityList.push('Abilene, TX')
    cityList.push('Akron, OH')
    cityList.push('Alamogordo, NM')
    cityList.push('Albany, GA')
    cityList.push('Albany, NY')
    cityList.push('Albany, OR')
    cityList.push('Albuquerque, NM')
    cityList.push('Alexandria, LA')
    cityList.push('Alexandria, MN')
    cityList.push('Allentown, PA')
    cityList.push('Alpena, MI')
    cityList.push('Altoona, PA')
    cityList.push('Altus, OK')
    cityList.push('Amarillo, TX')
    cityList.push('Ames, IA')
    cityList.push('Anchorage, AK')
    cityList.push('Anderson, IN')
    cityList.push('Anderson, SC')
    cityList.push('Andrews, TX')
    cityList.push('Ann Arbor, MI')
    cityList.push('Anniston, AL')
    cityList.push('Appleton, WI')
    cityList.push('Ardmore, OK')
    cityList.push('Asheville, NC')
    cityList.push('Astoria, OR')
    cityList.push('Athens, GA')
    cityList.push('Athens, TN')
    cityList.push('Atlanta, GA')
    cityList.push('Atlantic City, NJ')
    cityList.push('Auburn, AL')
    cityList.push('Auburn, IN')
    cityList.push('Augusta, GA')
    cityList.push('Augusta, ME')
    cityList.push('Austin, TX')
    cityList.push('Bakersfield, CA')
    cityList.push('Baltimore, MD')
    cityList.push('Bangor, ME')
    cityList.push('Batesville, AR')
    cityList.push('Baton Rouge, LA')
    cityList.push('Battle Creek, MI')
    cityList.push('Bay City, TX')
    cityList.push('Beaumont, TX')
    cityList.push('Beckley, WV')
    cityList.push('Bedford, IN')
    cityList.push('Bellingham, WA')
    cityList.push('Bemidji, MN')
    cityList.push('Bend, OR')
    cityList.push('Big Rapids, MI')
    cityList.push('Big Spring, TX')
    cityList.push('Billings, MT')
    cityList.push('Binghamton, NY')
    cityList.push('Birmingham, AL')
    cityList.push('Bishop, CA')
    cityList.push('Bismarck, ND')
    cityList.push('Blackfoot, ID')
    cityList.push('Bloomington, IL')
    cityList.push('Bloomington, IN')
    cityList.push('Blytheville, AR')
    cityList.push('Boston, MA')
    cityList.push('Bowling Green, KY')
    cityList.push('Bozeman, MT')
    cityList.push('Bradford, PA')
    cityList.push('Brainerd, MN')
    cityList.push('Branson, MO')
    cityList.push('Bremerton, WA')
    cityList.push('Bridgeport, CT')
    cityList.push('Brigham City, UT')
    cityList.push('Brookings, OR')
    cityList.push('Brookings, SD')
    cityList.push('Brownsville, TX')
    cityList.push('Brownwood, TX')
    cityList.push('Brunswick, GA')
    cityList.push('Buffalo, NY')
    cityList.push('Burley, ID')
    cityList.push('Burlington, IA')
    cityList.push('Burlington, VT')
    cityList.push('Butte, MT')
    cityList.push('Cadillac, MI')
    cityList.push('Cape Girardeau, MO')
    cityList.push('Carbondale, IL')
    cityList.push('Carlsbad, NM')
    cityList.push('Casper, WY')
    cityList.push('Cedar City, UT')
    cityList.push('Cedar Rapids, IA')
    cityList.push('Champaign, IL')
    cityList.push('Charleston, SC')
    cityList.push('Charleston, WV')
    cityList.push('Charlotte, NC')
    cityList.push('Charlottesville, VA')
    cityList.push('Chattanooga, TN')
    cityList.push('Cheyenne, WY')
    cityList.push('Chicago, IL')
    cityList.push('Chico, CA')
    cityList.push('Chillicothe, OH')
    cityList.push('Cincinnati, OH')
    cityList.push('Clarksburg, WV')
    cityList.push('Cleveland, OH')
    cityList.push('Clinton, IA')
    cityList.push('Clovis, NM')
    cityList.push('Coffeyville, KS')
    cityList.push('College Station, TX')
    cityList.push('Colorado Springs, CO')
    cityList.push('Columbia, MO')
    cityList.push('Columbia, SC')
    cityList.push('Columbia, TN')
    cityList.push('Columbus, GA')
    cityList.push('Columbus, IN')
    cityList.push('Columbus, MS')
    cityList.push('Columbus, NE')
    cityList.push('Columbus, OH')
    cityList.push('Connersville, IN')
    cityList.push('Corpus Christi, TX')
    cityList.push('Corsicana, TX')
    cityList.push('Crescent City, CA')
    cityList.push('Crossville, TN')
    cityList.push('Cumberland, MD')
    cityList.push('Dallas, TX')
    cityList.push('Dalton, GA')
    cityList.push('Danville, IL')
    cityList.push('Danville, KY')
    cityList.push('Dayton, OH')
    cityList.push('Decatur, AL')
    cityList.push('Decatur, IL')
    cityList.push('Del Rio, TX')
    cityList.push('Des Moines, IA')
    cityList.push('Detroit, MI')
    cityList.push('Dickinson, ND')
    cityList.push('Dodge City, KS')
    cityList.push('Dothan, AL')
    cityList.push('Dover, DE')
    cityList.push('Dubuque, IA')
    cityList.push('Duluth, MN')
    cityList.push('Durango, CO')
    cityList.push('Dyersburg, TN')
    cityList.push('Eagle Pass, TX')
    cityList.push('Easton, MD')
    cityList.push('Eau Claire, WI')
    cityList.push('El Centro, CA')
    cityList.push('El Dorado, AR')
    cityList.push('El Paso, TX')
    cityList.push('Elizabeth City, NC')
    cityList.push('Elizabethtown, KY')
    cityList.push('Elkhart, IN')
    cityList.push('Elko, NV')
    cityList.push('Ellensburg, WA')
    cityList.push('Elmira, NY')
    cityList.push('Enid, OK')
    cityList.push('Erie, PA')
    cityList.push('Escanaba, MI')
    cityList.push('Eugene, OR')
    cityList.push('Eureka, CA')
    cityList.push('Evansville, IN')
    cityList.push('Fairbanks, AK')
    cityList.push('Fallon, NV')
    cityList.push('Fargo, ND')
    cityList.push('Farmington, MO')
    cityList.push('Farmington, NM')
    cityList.push('Fayetteville, AR')
    cityList.push('Fayetteville, NC')
    cityList.push('Fergus Falls, MN')
    cityList.push('Findlay, OH')
    cityList.push('Flagstaff, AZ')
    cityList.push('Flint, MI')
    cityList.push('Florence, SC')
    cityList.push('Fort Dodge, IA')
    cityList.push('Fort Lauderdale, FL')
    cityList.push('Fort Leonard Wood, MO')
    cityList.push('Fort Smith, AR')
    cityList.push('Fort Wayne, IN')
    cityList.push('Frankfort, KY')
    cityList.push('Freeport, IL')
    cityList.push('Fremont, NE')
    cityList.push('Fresno, CA')
    cityList.push('Gadsden, AL')
    cityList.push('Gainesville, FL')
    cityList.push('Gainesville, GA')
    cityList.push('Galesburg, IL')
    cityList.push('Gallup, NM')
    cityList.push('Garden City, KS')
    cityList.push('Gary, IN')
    cityList.push('Georgetown, SC')
    cityList.push('Gillette, WY')
    cityList.push('Glens Falls, NY')
    cityList.push('Goldsboro, NC')
    cityList.push('Grand Forks, ND')
    cityList.push('Grand Island, NE')
    cityList.push('Grand Junction, CO')
    cityList.push('Grand Rapids, MI')
    cityList.push('Great Bend, KS')
    cityList.push('Great Falls, MT')
    cityList.push('Green Bay, WI')
    cityList.push('Greeneville, TN')
    cityList.push('Greensboro, NC')
    cityList.push('Greenville, MS')
    cityList.push('Greenville, NC')
    cityList.push('Greenville, SC')
    cityList.push('Greenwood, MS')
    cityList.push('Greenwood, SC')
    cityList.push('Grenada, MS')
    cityList.push('Gulfport, MS')
    cityList.push('Hagerstown, MD')
    cityList.push('Hanford, CA')
    cityList.push('Harrisburg, PA')
    cityList.push('Harrison, AR')
    cityList.push('Hartford, CT')
    cityList.push('Hastings, NE')
    cityList.push('Hattiesburg, MS')
    cityList.push('Havre, MT')
    cityList.push('Hays, KS')
    cityList.push('Helena, MT')
    cityList.push('Hickory, NC')
    cityList.push('Hilo, HI')
    cityList.push('Hobbs, NM')
    cityList.push('Holland, MI')
    cityList.push('Honolulu, HI')
    cityList.push('Hot Springs, AR')
    cityList.push('Houma, LA')
    cityList.push('Houston, TX')
    cityList.push('Hudson, NY')
    cityList.push('Huntsville, AL')
    cityList.push('Huron, SD')
    cityList.push('Hutchinson, KS')
    cityList.push('Idaho Falls, ID')
    cityList.push('Indiana, PA')
    cityList.push('Indianapolis, IN')
    cityList.push('Iron Mountain, MI')
    cityList.push('Ithaca, NY')
    cityList.push('Jackson, MI')
    cityList.push('Jackson, MS')
    cityList.push('Jackson, TN')
    cityList.push('Jackson, WY')
    cityList.push('Jacksonville, FL')
    cityList.push('Jacksonville, NC')
    cityList.push('Jamestown, ND')
    cityList.push('Jamestown, NY')
    cityList.push('Jefferson City, MO')
    cityList.push('Johnstown, PA')
    cityList.push('Jonesboro, AR')
    cityList.push('Joplin, MO')
    cityList.push('Juneau, AK')
    cityList.push('Kahului, HI')
    cityList.push('Kalamazoo, MI')
    cityList.push('Kalispell, MT')
    cityList.push('Kankakee, IL')
    cityList.push('Kansas City, MO')
    cityList.push('Kearney, NE')
    cityList.push('Kennewick, WA')
    cityList.push('Ketchikan, AK')
    cityList.push('Key West, FL')
    cityList.push('Killeen, TX')
    cityList.push('Kinston, NC')
    cityList.push('Kirksville, MO')
    cityList.push('Klamath Falls, OR')
    cityList.push('Knoxville, TN')
    cityList.push('Kodiak, AK')
    cityList.push('Kokomo, IN')
    cityList.push('La Crosse, WI')
    cityList.push('La Grande, OR')
    cityList.push('Laconia, NH')
    cityList.push('Lafayette, IN')
    cityList.push('Lafayette, LA')
    cityList.push('Lake Charles, LA')
    cityList.push('Lake City, FL')
    cityList.push('Lake Havasu City, AZ')
    cityList.push('Lakeland, FL')
    cityList.push('Lancaster, PA')
    cityList.push('Lansing, MI')
    cityList.push('Laramie, WY')
    cityList.push('Laredo, TX')
    cityList.push('Las Cruces, NM')
    cityList.push('Las Vegas, NV')
    cityList.push('Laurel, MS')
    cityList.push('Lawrence, KS')
    cityList.push('Lawrenceburg, TN')
    cityList.push('Lawton, OK')
    cityList.push('Lebanon, MO')
    cityList.push('Lewisburg, TN')
    cityList.push('Lewiston, ID')
    cityList.push('Lewiston, ME')
    cityList.push('Lexington, KY')
    cityList.push('Liberal, KS')
    cityList.push('Lima, OH')
    cityList.push('Lincoln, NE')
    cityList.push('Little Rock, AR')
    cityList.push('Lock Haven, PA')
    cityList.push('Logan, UT')
    cityList.push('London, KY')
    cityList.push('Longview, TX')
    cityList.push('Los Alamos, NM')
    cityList.push('Los Angeles, CA')
    cityList.push('Lubbock, TX')
    cityList.push('Lynchburg, VA')
    cityList.push('Macon, GA')
    cityList.push('Madera, CA')
    cityList.push('Madison, WI')
    cityList.push('Madisonville, KY')
    cityList.push('Manchester, NH')
    cityList.push('Manhattan, KS')
    cityList.push('Mankato, MN')
    cityList.push('Mansfield, OH')
    cityList.push('Marion, IL')
    cityList.push('Marion, IN')
    cityList.push('Marion, OH')
    cityList.push('Marquette, MI')
    cityList.push('Marshall, MN')
    cityList.push('Marshall, MO')
    cityList.push('Marshall, TX')
    cityList.push('Marshalltown, IA')
    cityList.push('Mason City, IA')
    cityList.push('Meadville, PA')
    cityList.push('Medford, OR')
    cityList.push('Memphis, TN')
    cityList.push('Merced, CA')
    cityList.push('Meridian, MS')
    cityList.push('Miami, FL')
    cityList.push('Miami, OK')
    cityList.push('Midland, TX')
    cityList.push('Milwaukee, WI')
    cityList.push('Minneapolis, MN')
    cityList.push('Minot, ND')
    cityList.push('Missoula, MT')
    cityList.push('Mobile, AL')
    cityList.push('Modesto, CA')
    cityList.push('Monroe, LA')
    cityList.push('Montgomery, AL')
    cityList.push('Montrose, CO')
    cityList.push('Morgantown, WV')
    cityList.push('Morristown, TN')
    cityList.push('Moses Lake, WA')
    cityList.push('Mount Pleasant, MI')
    cityList.push('Mount Pleasant, TX')
    cityList.push('Mount Sterling, KY')
    cityList.push('Mount Vernon, IL')
    cityList.push('Mount Vernon, WA')
    cityList.push('Mountain Home, AR')
    cityList.push('Mountain Home, ID')
    cityList.push('Muncie, IN')
    cityList.push('Muscatine, IA')
    cityList.push('Muskegon, MI')
    cityList.push('Myrtle Beach, SC')
    cityList.push('Nacogdoches, TX')
    cityList.push('Napa, CA')
    cityList.push('Naples, FL')
    cityList.push('Nashville, TN')
    cityList.push('New Bern, NC')
    cityList.push('New Haven, CT')
    cityList.push('New Iberia, LA')
    cityList.push('New Orleans, LA')
    cityList.push('New Philadelphia, OH')
    cityList.push('New York, NY')
    cityList.push('Newark, NJ')
    cityList.push('Nogales, AZ')
    cityList.push('Norfolk, NE')
    cityList.push('North Platte, NE')
    cityList.push('Oak Harbor, WA')
    cityList.push('Oakland, CA')
    cityList.push('Ocala, FL')
    cityList.push('Ogden, UT')
    cityList.push('Ogdensburg, NY')
    cityList.push('Oklahoma City, OK')
    cityList.push('Olympia, WA')
    cityList.push('Omaha, NE')
    cityList.push('Oneonta, NY')
    cityList.push('Orangeburg, SC')
    cityList.push('Orlando, FL')
    cityList.push('Oshkosh, WI')
    cityList.push('Owatonna, MN')
    cityList.push('Owensboro, KY')
    cityList.push('Oxnard, CA')
    cityList.push('Paducah, KY')
    cityList.push('Panama City, FL')
    cityList.push('Paris, TN')
    cityList.push('Parkersburg, WV')
    cityList.push('Pendleton, OR')
    cityList.push('Pensacola, FL')
    cityList.push('Peoria, IL')
    cityList.push('Peru, IN')
    cityList.push('Philadelphia, PA')
    cityList.push('Phoenix, AZ')
    cityList.push('Pierre, SD')
    cityList.push('Pine Bluff, AR')
    cityList.push('Pittsburgh, PA')
    cityList.push('Pittsfield, MA')
    cityList.push('Plattsburgh, NY')
    cityList.push('Pocatello, ID')
    cityList.push('Ponca City, OK')
    cityList.push('Port Angeles, WA')
    cityList.push('Portland, ME')
    cityList.push('Portland, OR')
    cityList.push('Poughkeepsie, NY')
    cityList.push('Prescott, AZ')
    cityList.push('Price, UT')
    cityList.push('Prineville, OR')
    cityList.push('Providence, RI')
    cityList.push('Provo, UT')
    cityList.push('Pueblo, CO')
    cityList.push('Pullman, WA')
    cityList.push('Punta Gorda, FL')
    cityList.push('Quincy, IL')
    cityList.push('Racine, WI')
    cityList.push('Raleigh, NC')
    cityList.push('Rapid City, SD')
    cityList.push('Reading, PA')
    cityList.push('Red Bluff, CA')
    cityList.push('Redding, CA')
    cityList.push('Reno, NV')
    cityList.push('Rexburg, ID')
    cityList.push('Richmond, IN')
    cityList.push('Richmond, KY')
    cityList.push('Richmond, VA')
    cityList.push('Riverside, CA')
    cityList.push('Riverton, WY')
    cityList.push('Roanoke, VA')
    cityList.push('Rochester, MN')
    cityList.push('Rochester, NY')
    cityList.push('Rock Springs, WY')
    cityList.push('Rockford, IL')
    cityList.push('Rockland, ME')
    cityList.push('Rocky Mount, NC')
    cityList.push('Rome, GA')
    cityList.push('Roseburg, OR')
    cityList.push('Roswell, NM')
    cityList.push('Ruidoso, NM')
    cityList.push('Russellville, AR')
    cityList.push('Ruston, LA')
    cityList.push('Rutland, VT')
    cityList.push('Sacramento, CA')
    cityList.push('Safford, AZ')
    cityList.push('Saginaw, MI')
    cityList.push('Salem, OR')
    cityList.push('Salina, KS')
    cityList.push('Salinas, CA')
    cityList.push('Salisbury, MD')
    cityList.push('Salisbury, NC')
    cityList.push('Salt Lake City, UT')
    cityList.push('San Angelo, TX')
    cityList.push('San Antonio, TX')
    cityList.push('San Diego, CA')
    cityList.push('San Francisco, CA')
    cityList.push('San Jose, CA')
    cityList.push('San Luis Obispo, CA')
    cityList.push('Sandusky, OH')
    cityList.push('Santa Ana, CA')
    cityList.push('Santa Barbara, CA')
    cityList.push('Santa Fe, NM')
    cityList.push('Santa Rosa, CA')
    cityList.push('Savannah, GA')
    cityList.push('Scottsbluff, NE')
    cityList.push('Scranton, PA')
    cityList.push('Searcy, AR')
    cityList.push('Seattle, WA')
    cityList.push('Selma, AL')
    cityList.push('Seymour, IN')
    cityList.push('Shawnee, OK')
    cityList.push('Sheboygan, WI')
    cityList.push('Shelby, NC')
    cityList.push('Shelbyville, TN')
    cityList.push('Shelton, WA')
    cityList.push('Sheridan, WY')
    cityList.push('Show Low, AZ')
    cityList.push('Shreveport, LA')
    cityList.push('Sikeston, MO')
    cityList.push('Silver City, NM')
    cityList.push('Sioux City, IA')
    cityList.push('Sioux Falls, SD')
    cityList.push('Somerset, KY')
    cityList.push('South Bend, IN')
    cityList.push('Spartanburg, SC')
    cityList.push('Spokane, WA')
    cityList.push('Springfield, IL')
    cityList.push('Springfield, MO')
    cityList.push('Springfield, OH')
    cityList.push('St.Cloud, MN')
    cityList.push('St.George, UT')
    cityList.push('St.Joseph, MO')
    cityList.push('St.Louis, MO')
    cityList.push('Starkville, MS')
    cityList.push('State College, PA')
    cityList.push('Statesboro, GA')
    cityList.push('Statesville, NC')
    cityList.push('Staunton, VA')
    cityList.push('Sterling, CO')
    cityList.push('Sterling, IL')
    cityList.push('Stillwater, OK')
    cityList.push('Stockton, CA')
    cityList.push('Storm Lake, IA')
    cityList.push('Sturgis, MI')
    cityList.push('Sumter, SC')
    cityList.push('Sweetwater, TX')
    cityList.push('Syracuse, NY')
    cityList.push('Tacoma, WA')
    cityList.push('Talladega, AL')
    cityList.push('Tallahassee, FL')
    cityList.push('Tampa, FL')
    cityList.push('Taos, NM')
    cityList.push('Terre Haute, IN')
    cityList.push('Thomasville, GA')
    cityList.push('Toledo, OH')
    cityList.push('Topeka, KS')
    cityList.push('Traverse City, MI')
    cityList.push('Trenton, NJ')
    cityList.push('Truckee, CA')
    cityList.push('Tucson, AZ')
    cityList.push('Tullahoma, TN')
    cityList.push('Tulsa, OK')
    cityList.push('Tupelo, MS')
    cityList.push('Tuscaloosa, AL')
    cityList.push('Twin Falls, ID')
    cityList.push('Tyler, TX')
    cityList.push('Ukiah, CA')
    cityList.push('Union City, TN')
    cityList.push('Utica, NY')
    cityList.push('Uvalde, TX')
    cityList.push('Valdosta, GA')
    cityList.push('Vernal, UT')
    cityList.push('Victoria, TX')
    cityList.push('Visalia, CA')
    cityList.push('Waco, TX')
    cityList.push('Walla Walla, WA')
    cityList.push('Wapakoneta, OH')
    cityList.push('Warrensburg, MO')
    cityList.push('Washington Court House, OH')
    cityList.push('Washington, DC')
    cityList.push('Waterloo, IA')
    cityList.push('Watertown, NY')
    cityList.push('Watertown, SD')
    cityList.push('Wausau, WI')
    cityList.push('Waycross, GA')
    cityList.push('Wenatchee, WA')
    cityList.push('West Palm Beach, FL')
    cityList.push('Wheeling, WV')
    cityList.push('Wichita Falls, TX')
    cityList.push('Wichita, KS')
    cityList.push('Williamsport, PA')
    cityList.push('Williston, ND')
    cityList.push('Wilmington, DE')
    cityList.push('Wilmington, NC')
    cityList.push('Wilmington, OH')
    cityList.push('Winchester, VA')
    cityList.push('Wooster, OH')
    cityList.push('Worcester, MA')
    cityList.push('Yakima, WA')
    cityList.push('Yankton, SD')
    cityList.push('York, PA')
    cityList.push('Youngstown, OH')
    cityList.push('Yuma, AZ')
    cityList.push('Zanesville, OH')

    return cityList
}

function getMonths(months) {
    months.push('January')
    months.push('February')
    months.push('March')
    months.push('April')
    months.push('May')
    months.push('June')
    months.push('July')
    months.push('August')
    months.push('September')
    months.push('October')
    months.push('November')
    months.push('December')

    return months
}

module.exports =
{
    getCityList: getCityList,
    getMonths: getMonths
}